repo: "using-svg-icons"
canvasCourse: "web-design-2"

inherit:
  - naming-restrict-live
  - git-2
  - html
  - css
  - border-box

html:
  - path: "index.html"
    outline: false
    has:
      - "ul > li > a > i.icon > svg > use"
      - "ul > li:nth-child(3)"
    search:
      - "#brachiosaurus"
      - "#micropachycephalosaurus"
      - "#velociraptor"
      - "Brachiosaurus"
      - "Micropachycephalosaurus"
      - "Velociraptor"

css:
  - path: "css/main.css"
    has:
      - ["html", "text-size-adjust", "100%"]
      - ["html", "-webkit-text-size-adjust", "100%"]
      - ["ul", "display", "grid"]
      - ["a", "color", "#76a500"]
      - ["a", "display", "flex"]
      - ["a:hover", "color", "#acc300"]
      - ".icon"
      - ".icon svg"

screenshots:
  - path: "index.html"
    label: "Before"
    sizes: [650]
  - path: "index.html"
    label: "After"
    useAnimations: true
    sizes: [650]
    before: |
      hover('ul > li > a', done);

functionality:
  - path: "index.html"
    tests:
      - |
        let link = $('ul > li > a');
        let oldBg = css(link).color;

        hover(link, function () {
          if (css(link).color == oldBg) return fail('The colour of the icon links doesn’t change when hovered');
          pass();
        });
